# Titel der Webseite (Das steht ganz oben links im Menü)
title: "MBSE Architecture Framework"

# Kurze Beschreibung Ihrer Seite
description: "Ein System Architecture Framework basierend auf MBSE."

# Das Design-Thema – HIER DARF NUR DIESER TEXT STEHEN:
theme: "just-the-docs"

# Steuert die URL-Struktur auf GitHub Pages
remote_theme: just-the-docs/just-the-docs

# Einstellungen für die eingebaute Suchfunktion
search_enabled: true
search:
  tokenizer: separator
  separator: '[\s\-\.]+'
  
